FROM mamonu/moj-spark-jovyan:baseenv

RUN pip install pytest pytest-cov poetry coveralls typeguard
RUN pip install --no-dependencies splink-data-generation==1.0.0

ADD . /myfiles
WORKDIR /myfiles


ENTRYPOINT ["/myfiles/testrunner_entrypoint.sh"]
