FROM mamonu/moj-spark-jovyan:baseenv

RUN pip install pytest pytest-cov poetry coveralls
RUN pip install --no-dependencies splink-data-generation

ADD . /myfiles
WORKDIR /myfiles


ENTRYPOINT ["/myfiles/testrunner_entrypoint.sh"]
