from __future__ import annotations

from typing import (
    TYPE_CHECKING,
    Any,
    Dict,
    Iterable,
    List,
    Optional,
    Union,
    cast,
)

from splink.internals.blocking import BlockingRule, user_input_link_type_options
from splink.internals.blocking_analysis import (
    CumulativeComparisonRecord,
    _as_blocking_rule,
    _cumulative_comparisons_to_be_scored_from_blocking_rules,
    n_largest_blocks,
)
from splink.internals.blocking_rule_creator import BlockingRuleCreator
from splink.internals.charts import (
    CumulativeBlockingRuleComparisonsGeneratedChart,
)
from splink.internals.splink_dataframe import SplinkDataFrame

if TYPE_CHECKING:
    from splink.internals.linker import Linker


class LinkerBlockingAnalysis:
    """Analyse blocking rules in the context of a linker.  Accessed via
    `linker.blocking_analysis`.

    These methods mirror the standalone functions in `splink.blocking_analysis`,
    but read the input data, link type, unique id column and source dataset column
    from the linker's settings, so you don't have to pass them in.
    """

    def __init__(self, linker: Linker):
        self._linker = linker

    def _default_blocking_rules(self) -> List[BlockingRule]:
        settings = self._linker._settings_obj
        rules = settings._blocking_rules_to_generate_predictions
        if not rules:
            raise ValueError(
                "No blocking_rules_to_generate_predictions were found in the "
                "linker's settings.  Either add them to your settings or pass "
                "blocking_rules explicitly to this method."
            )
        return rules

    def count_comparisons_from_blocking_rules(
        self,
        blocking_rules: Iterable[
            BlockingRuleCreator | BlockingRule | str | dict[str, Any]
        ]
        | None = None,
        *,
        record_sample_proportion: float = 0.05,
    ) -> list[CumulativeComparisonRecord]:
        """Analyse one or more blocking rules to understand how many comparisons
        they will generate, using the data and settings from this linker.

        A single record is returned per blocking rule.  When multiple rules are
        provided, the marginal and cumulative number of comparisons generated by
        each rule are computed.

        Args:
            blocking_rules (optional): The blocking rules to analyse.  If not
                provided, the blocking_rules_to_generate_predictions from the
                linker's settings are used.
            record_sample_proportion (float, optional): The sampling proportion
                applied to each side of the blocking join. Defaults to ``0.05``,
                meaning Splink estimates the count from a deterministic 5% sample of
                input records on each side of the blocking join. Set
                ``record_sample_proportion=1.0`` to compute exact counts.

        Returns:
            list[CumulativeComparisonRecord]: One record per blocking rule.
        """
        blocking_rules_as_br = self._resolve_blocking_rules(blocking_rules)
        settings = self._linker._settings_obj

        return _cumulative_comparisons_to_be_scored_from_blocking_rules(
            splink_df_dict=self._linker._input_tables_dict,
            blocking_rules=blocking_rules_as_br,
            link_type=settings._link_type,
            db_api=self._linker._db_api,
            unique_id_input_column=settings.column_info_settings.unique_id_input_column,
            source_dataset_input_column=settings.column_info_settings.source_dataset_input_column,
            record_sample_proportion=record_sample_proportion,
        )

    def chart_comparisons_from_blocking_rules(
        self,
        blocking_rules: Optional[
            Iterable[Union[BlockingRuleCreator, BlockingRule, str, Dict[str, Any]]]
        ] = None,
        *,
        record_sample_proportion: float = 0.05,
    ) -> CumulativeBlockingRuleComparisonsGeneratedChart:
        """Produce a chart of the cumulative number of comparisons generated by one
        or more blocking rules, using the data and settings from this linker.

        Args:
            blocking_rules (optional): The blocking rules to analyse.  If not
                provided, the blocking_rules_to_generate_predictions from the
                linker's settings are used.
            record_sample_proportion (float, optional): Defaults to ``0.05``. See
                ``count_comparisons_from_blocking_rules`` for details.

        Returns:
            CumulativeBlockingRuleComparisonsGeneratedChart: The chart.
        """
        records = self.count_comparisons_from_blocking_rules(
            blocking_rules,
            record_sample_proportion=record_sample_proportion,
        )
        return CumulativeBlockingRuleComparisonsGeneratedChart(records)

    def n_largest_blocks(
        self,
        blocking_rule: Union[BlockingRuleCreator, BlockingRule, str, Dict[str, Any]],
        *,
        n_largest: int = 5,
    ) -> SplinkDataFrame:
        """Find the values responsible for creating the largest blocks of records,
        using the data and settings from this linker.

        Args:
            blocking_rule: The blocking rule to analyse.
            n_largest (int, optional): How many rows to return. Defaults to 5.

        Returns:
            SplinkDataFrame: A dataframe containing the n_largest blocks.
        """
        settings = self._linker._settings_obj
        return n_largest_blocks(
            list(self._linker._input_tables_dict.values()),
            blocking_rule=blocking_rule,
            link_type=cast(user_input_link_type_options, settings._link_type),
            n_largest=n_largest,
        )

    def _resolve_blocking_rules(
        self,
        blocking_rules: Iterable[
            BlockingRuleCreator | BlockingRule | str | dict[str, Any]
        ]
        | None,
    ) -> List[BlockingRule]:
        if blocking_rules is None:
            return self._default_blocking_rules()

        sql_dialect_str = self._linker._db_api.sql_dialect.sql_dialect_str
        return [_as_blocking_rule(br, sql_dialect_str) for br in blocking_rules]
