from __future__ import annotations

from typing import (
    TYPE_CHECKING,
    Any,
    Dict,
    Iterable,
    List,
    Literal,
    Optional,
    Union,
    cast,
)

from splink.internals.blocking import BlockingRule, user_input_link_type_options
from splink.internals.blocking_analysis import (
    CumulativeComparisonRecord,
    _as_blocking_rule,
    _count_comparisons_generated_from_blocking_rule,
    _cumulative_comparisons_to_be_scored_from_blocking_rules,
    n_largest_blocks,
)
from splink.internals.blocking_rule_creator import BlockingRuleCreator
from splink.internals.charts import (
    CumulativeBlockingRuleComparisonsGeneratedChart,
)
from splink.internals.splink_dataframe import SplinkDataFrame

if TYPE_CHECKING:
    from splink.internals.linker import Linker


class LinkerBlockingAnalysis:
    """Analyse blocking rules in the context of a linker.  Accessed via
    `linker.blocking_analysis`.

    These methods mirror the standalone functions in `splink.blocking_analysis`,
    but read the input data, link type, unique id column and source dataset column
    from the linker's settings, so you don't have to pass them in.
    """

    def __init__(self, linker: Linker):
        self._linker = linker

    def _default_blocking_rules(self) -> List[BlockingRule]:
        settings = self._linker._settings_obj
        rules = settings._blocking_rules_to_generate_predictions
        if not rules:
            raise ValueError(
                "No blocking_rules_to_generate_predictions were found in the "
                "linker's settings.  Either add them to your settings or pass "
                "blocking_rules explicitly to this method."
            )
        return rules

    def count_comparisons_from_blocking_rule(
        self,
        blocking_rule: Union[BlockingRuleCreator, BlockingRule, str, Dict[str, Any]],
        *,
        compute_post_filter_count: bool = True,
        max_rows_limit: int = int(1e9),
        count_method: Literal["exact", "estimate"] = "exact",
        probe_proportion: float = 0.01,
    ) -> dict[str, Union[int, float, str, None]]:
        """Analyse a blocking rule to understand the number of comparisons it
        will generate, using the data and settings from this linker.

        Args:
            blocking_rule: The blocking rule to analyse.
            compute_post_filter_count (bool, optional): Whether to use a slower
                methodology to calculate how many comparisons will be generated
                post filter conditions. Defaults to True.
            max_rows_limit (int, optional): Calculation of post filter counts will
                only proceed if the fast method returns a value below this limit.
                Defaults to int(1e9).
            count_method (Literal["exact", "estimate"], optional): How to compute
                the post-filter count.  "estimate" samples both sides of the
                blocking join and scales the result back up, which is much faster
                for large datasets at the cost of some accuracy.  The pre-filter
                count is always exact.  Defaults to "exact".
            probe_proportion (float, optional): The sampling proportion applied to
                each side of the join when ``count_method="estimate"``. Defaults to
                0.01.

        Returns:
            dict[str, Union[int, float, str, None]]: A dictionary containing the
            results.
        """
        settings = self._linker._settings_obj
        blocking_rule_as_br = _as_blocking_rule(
            blocking_rule, self._linker._db_api.sql_dialect.sql_dialect_str
        )

        return _count_comparisons_generated_from_blocking_rule(
            splink_df_dict=self._linker._input_tables_dict,
            blocking_rule=blocking_rule_as_br,
            link_type=settings._link_type,
            db_api=self._linker._db_api,
            compute_post_filter_count=compute_post_filter_count,
            max_rows_limit=max_rows_limit,
            unique_id_input_column=settings.column_info_settings.unique_id_input_column,
            source_dataset_input_column=settings.column_info_settings.source_dataset_input_column,
            count_method=count_method,
            probe_proportion=probe_proportion,
        )

    def cumulative_comparisons_to_be_scored_from_blocking_rules_data(
        self,
        blocking_rules: Optional[
            Iterable[Union[BlockingRuleCreator, BlockingRule, str, Dict[str, Any]]]
        ] = None,
        *,
        max_rows_limit: int = int(1e9),
        count_method: Literal["exact", "estimate"] = "exact",
        probe_proportion: float = 0.01,
    ) -> list[CumulativeComparisonRecord]:
        """Compute the cumulative number of comparisons generated by a sequence of
        blocking rules, using the data and settings from this linker.

        Args:
            blocking_rules (optional): The blocking rules to analyse.  If not
                provided, the blocking_rules_to_generate_predictions from the
                linker's settings are used.
            max_rows_limit (int, optional): Defaults to int(1e9).
            count_method (Literal["exact", "estimate"], optional): Defaults to
                "exact".  See ``count_comparisons_from_blocking_rule`` for details.
            probe_proportion (float, optional): Defaults to 0.01.

        Returns:
            list[CumulativeComparisonRecord]: One record per blocking rule.
        """
        blocking_rules_as_br = self._resolve_blocking_rules(blocking_rules)
        settings = self._linker._settings_obj

        return _cumulative_comparisons_to_be_scored_from_blocking_rules(
            splink_df_dict=self._linker._input_tables_dict,
            blocking_rules=blocking_rules_as_br,
            link_type=settings._link_type,
            db_api=self._linker._db_api,
            max_rows_limit=max_rows_limit,
            unique_id_input_column=settings.column_info_settings.unique_id_input_column,
            source_dataset_input_column=settings.column_info_settings.source_dataset_input_column,
            count_method=count_method,
            probe_proportion=probe_proportion,
        )

    def cumulative_comparisons_to_be_scored_from_blocking_rules_chart(
        self,
        blocking_rules: Optional[
            Iterable[Union[BlockingRuleCreator, BlockingRule, str, Dict[str, Any]]]
        ] = None,
        *,
        max_rows_limit: int = int(1e9),
        count_method: Literal["exact", "estimate"] = "exact",
        probe_proportion: float = 0.01,
    ) -> CumulativeBlockingRuleComparisonsGeneratedChart:
        """Produce a chart of the cumulative number of comparisons generated by a
        sequence of blocking rules, using the data and settings from this linker.

        Args:
            blocking_rules (optional): The blocking rules to analyse.  If not
                provided, the blocking_rules_to_generate_predictions from the
                linker's settings are used.
            max_rows_limit (int, optional): Defaults to int(1e9).
            count_method (Literal["exact", "estimate"], optional): Defaults to
                "exact".  See ``count_comparisons_from_blocking_rule`` for details.
            probe_proportion (float, optional): Defaults to 0.01.

        Returns:
            CumulativeBlockingRuleComparisonsGeneratedChart: The chart.
        """
        records = self.cumulative_comparisons_to_be_scored_from_blocking_rules_data(
            blocking_rules,
            max_rows_limit=max_rows_limit,
            count_method=count_method,
            probe_proportion=probe_proportion,
        )
        return CumulativeBlockingRuleComparisonsGeneratedChart(records)

    def n_largest_blocks(
        self,
        blocking_rule: Union[BlockingRuleCreator, BlockingRule, str, Dict[str, Any]],
        *,
        n_largest: int = 5,
    ) -> SplinkDataFrame:
        """Find the values responsible for creating the largest blocks of records,
        using the data and settings from this linker.

        Args:
            blocking_rule: The blocking rule to analyse.
            n_largest (int, optional): How many rows to return. Defaults to 5.

        Returns:
            SplinkDataFrame: A dataframe containing the n_largest blocks.
        """
        settings = self._linker._settings_obj
        return n_largest_blocks(
            list(self._linker._input_tables_dict.values()),
            blocking_rule=blocking_rule,
            link_type=cast(user_input_link_type_options, settings._link_type),
            n_largest=n_largest,
        )

    def _resolve_blocking_rules(
        self,
        blocking_rules: Optional[
            Iterable[Union[BlockingRuleCreator, BlockingRule, str, Dict[str, Any]]]
        ],
    ) -> List[BlockingRule]:
        if blocking_rules is None:
            return self._default_blocking_rules()

        # Allow either a single blocking rule or an iterable of them
        if isinstance(blocking_rules, (str, dict, BlockingRuleCreator, BlockingRule)):
            rules_list: List[
                Union[BlockingRuleCreator, BlockingRule, str, Dict[str, Any]]
            ] = [blocking_rules]
        else:
            rules_list = list(blocking_rules)

        sql_dialect_str = self._linker._db_api.sql_dialect.sql_dialect_str
        return [_as_blocking_rule(br, sql_dialect_str) for br in rules_list]
