pi_iteration_chart_def = {'config': {'view': {'width': 400, 'height': 300},
                                'mark': {'tooltip': None},
                                'title': {'anchor': 'middle'}},
                     'hconcat': [{'mark': 'bar',
                                  'encoding': {'color': {'type': 'nominal', 'field': 'value'},
                                               'row': {'type': 'nominal', 'field': 'column', 'sort': {'field': 'gamma'}},
                                               'tooltip': [{'type': 'quantitative', 'field': 'probability'},
                                                           {'type': 'ordinal',
                                                            'field': 'iteration'},
                                                           {'type': 'nominal',
                                                               'field': 'column'},
                                                           {'type': 'nominal', 'field': 'value'}],
                                               'x': {'type': 'ordinal', 'field': 'iteration'},
                                               'y': {'type': 'quantitative',
                                                     'aggregate': 'sum',
                                                     'axis': {'title': '𝛾 value'},
                                                     'field': 'probability'}},
                                  'height': 100,
                                  'resolve': {'scale': {'y': 'independent'}},
                                  'title': 'Non Match',
                                  'transform': [{'filter': '(datum.match === 0)'}]},
                                 {'mark': 'bar',
                                  'encoding': {'color': {'type': 'nominal', 'field': 'value'},
                                               'row': {'type': 'nominal', 'field': 'column', 'sort': {'field': 'gamma'}},
                                               'tooltip': [{'type': 'quantitative', 'field': 'probability'},
                                                           {'type': 'ordinal',
                                                            'field': 'iteration'},
                                                           {'type': 'nominal',
                                                            'field': 'column'},
                                                           {'type': 'nominal', 'field': 'value'}],
                                               'x': {'type': 'ordinal', 'field': 'iteration'},
                                               'y': {'type': 'quantitative',
                                                     'aggregate': 'sum',
                                                     'axis': {'title': '𝛾 value'},
                                                     'field': 'probability'}},
                                  'height': 100,
                                  'resolve': {'scale': {'y': 'independent'}},
                                  'title': 'Match',
                                  'transform': [{'filter': '(datum.match === 1)'}]}],
                     'data': {'values': None},
                     'title': 'Probability distribution of comparison vector values by iteration number',
                     '$schema': 'https://vega.github.io/schema/vega-lite/v3.4.0.json'}


lambda_iteration_chart_def = {'config': {'view': {'width': 400, 'height': 300}, 'mark': {'tooltip': None}},
                     'data': {'values': None},
                     'mark': 'bar',
                     'encoding': {'x': {'type': 'ordinal', 'field': 'iteration'},

                                  'y': {'type': 'quantitative',
                                        'axis': {'title': 'λ (estimated proportion of matches)'},
                                        'field': 'λ'},
                                  'tooltip': [{'type': 'quantitative', 'field': 'λ'},
                                 {'type': 'ordinal',
                                  'field': 'iteration'}]},
                                                      'title': 'Lambda value by iteration',
                     '$schema': 'https://vega.github.io/schema/vega-lite/v3.4.0.json'}


probability_distribution_chart = chart_def = {'config': {'view': {'width': 400, 'height': 300},
                                'mark': {'tooltip': None},
                                'title': {'anchor': 'middle'}},
                     'hconcat': [{'mark': 'bar',
                                  'encoding': {'color': {'type': 'nominal', 'field': 'match'},
                                               'row': {'type': 'nominal', 'field': 'column', 'sort': {'field': 'gamma'}},
                                               'tooltip': [{'type': 'nominal', 'field': 'column'},
                                                           {'type': 'quantitative',
                                                            'field': 'probability', 'format': '.4f'},
                                                           {'type': 'ordinal', 'field': 'value'}],
                                               'x': {'type': 'quantitative', 'field': 'probability'},
                                               'y': {'type': 'nominal', 'axis': {'title': '𝛾 value'}, 'field': 'value'}},
                                  'resolve': {'scale': {'y': 'independent'}},
                                  'transform': [{'filter': '(datum.match === 0)'}],
                                  'width': 150},
                                 {'mark': 'bar',
                                  'encoding': {'color': {'type': 'nominal', 'field': 'match'},
                                               'row': {'type': 'nominal', 'field': 'column', 'sort': {'field': 'gamma'}},
                                               'tooltip': [{'type': 'nominal', 'field': 'column'},
                                                           {'type': 'quantitative',
                                                            'field': 'probability', 'format': '.4f'},
                                                           {'type': 'ordinal', 'field': 'value'}],
                                               'x': {'type': 'quantitative', 'field': 'probability'},
                                               'y': {'type': 'nominal', 'axis': {'title': '𝛾 value'}, 'field': 'value'}},
                                  'resolve': {'scale': {'y': 'independent'}},
                                  'transform': [{'filter': '(datum.match === 1)'}],
                                  'width': 150}],
                     'data': {'values': None},
                     'title': 'Probability distribution of comparison vector values, m=0 and m=1',
                     '$schema': 'https://vega.github.io/schema/vega-lite/v3.4.0.json'}