name: Check lockfile

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "uv.lock"

permissions: {}

jobs:
  lockfile-check:
    name: Check lockfile is up to date
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup uv (without cache)
        id: setup_uv
        uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
        with:
          enable-cache: false

      - name: Check uv.lock is up to date
        id: check_lockfile
        run: uv lock --check
