name: Dependency review

on:
  pull_request:
    branches:
      - master
      - "**dev"

permissions: {}

jobs:
  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Dependency Review
        id: dependency_review
        uses: actions/dependency-review-action@05fe4576374b728f0c523d6a13d64c25081e0803 # v4.8.3
        with:
          comment-summary-in-pr: true
          fail-on-severity: critical
